# name
name: hello_world

# trigger -> condition that trigger workflow
on:
- push

# one or more jobs
jobs:
  cow:
    name: Cowsays
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'

